### ISSUE TITLE
Document the `dwgd.route` option in the readme

### ISSUE THREAD

**Issue by pcouy** [leomos/dwgd#4]
Hi ! After coming up with my own hacky solution to use the wireguard interface as the default route inside the containers, I looked into properly adding it to your plugin. That's when I noticed the `dwgd.route` option in your code.

Do I understand correctly that adding the following line to my `docker-compose.yml` will route all traffic that is not local to the default docker network through my wireguard peer ?

```yml
networks:
  wgnet:
    driver: dwgd
    driver_opts:
      dwgd.route: 0.0.0.0/0
      [...other options documented in the readme]
```

If you confirm this is correct, I will submit a pull request to document this in the README.
